name: CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          script: |
            mkdir -p ~/.ssh
            echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }}
            cd ~/apps/website
            git pull origin main
            pnpm run install
            pnpm run build
            cp -r ./dist/* /var/www/website
